### PR TITLE
Fixed French errors

### PR DESCRIPTION
**Pull request by theute**
I only reviewed about the first half at this point, will finish if this gets merged.

### CODE REVIEW

**Comment by theute** [comment]
The code coverage can't have decreased because of translations ;)

**Comment by syjer** [comment]
hi @theute , thank you for the PR, I'll have a look and merge it ASAP. 👍

**Comment by syjer** [comment]
@theute I've merged the PR, thank you :+1:

**Comment by vorburger** [comment]
@theute so cool to see you also contribute here! 

@syjer @cbellone I told Thomas that I ran https://tickets.learn.study on Alf.io yesterday... :smile: BTW #528

**Pull request merged**
