### PR TITLE
#1269 Resolved the bug to show correct {{eventName}} on compose message page

### PR DESCRIPTION
**Pull request by ved-asole**
Resolved the bug #1269 to show show correct {{eventName}} on compose message page

### CODE REVIEW

**Comment by ved-asole** [comment]
@cbellone - Could you please approve the above bug fix for the bug #1269?

**Comment by cbellone** [comment]
Hi @ved-asole thanks for the modification.

I am afraid this does not solve the issue completely. You have to make sure that event.displayName is also used in the actual email being sent (see original bug).

If you're testing locally, you can see the email output on the console and check if the output is the expected one. Feel free to create an (unit) test case for this. It would be highly appreciated

**Comment by ved-asole** [comment]
Hi @cbellone, sure. I will also check the actual email.

**Comment by ved-asole** [comment]
Hi @cbellone, I have updated the code to sent the correct eventName in the actual email also

**Comment by ved-asole** [comment]
Hi @cbellone, Could you please approve the above pull request?

**Comment by cbellone** [comment]
I can't approve the pull request because I don't think it solves the issue.
I don't know what you're trying to do [here](https://github.com/alfio-event/alf.io/pull/1275/files/187da43bbea9e8876e4bf4d3de68854fb2a44b74..c51d8c10c7248c4352de74f293c02bf3425aa9e0#diff-79295be9220e97402bfbf9dc01133b5dcadc01a4c15e32f2476471f9b9c18d8dR70) but you shouldn't be supposed to change select statements for solving this issue.

Have you tested the application and verified that your fix is working? Because I'd be very surprised if it did...

**Comment by ved-asole** [comment]
Hi @cbellone, so what happened is that at first the angular ui was showing the wrong value for eventName. When I corrected that then that value was sent in api call to the backend and in backend it was checking for that value with the DB for short name whereas it should have  checked for displayName. So I updated the select statement to check for display Name also as that method is used by other functions so I can't remove the check for shortName. 


Please find below the screenshots where it works for me :

Email_Issue_Resolution

**Comment by ved-asole** [comment]
> I can't approve the pull request because I don't think it solves the issue. I don't know what you're trying to do [here](https://github.com/alfio-event/alf.io/pull/1275/files/187da43bbea9e8876e4bf4d3de68854fb2a44b74..c51d8c10c7248c4352de74f293c02bf3425aa9e0#diff-79295be9220e97402bfbf9dc01133b5dcadc01a4c15e32f2476471f9b9c18d8dR70) but you shouldn't be supposed to change select statements for solving this issue.
> 
> Have you tested the application and verified that your fix is working? Because I'd be very surprised if it did...

If you want, I can created a new method for the same to get display Name rather than changing the select statement because that method is used by around 4 other functions to get the short Name so I can't remove short name also.

**Comment by cbellone** [comment]
OK, thanks for your detailed explanation. I now understand what's wrong and what caused the query modification.
You have modified [a $scope property](https://github.com/alfio-event/alf.io/pull/1275/commits/187da43bbea9e8876e4bf4d3de68854fb2a44b74#diff-cfbf5c58992e0c406f9df7f9ebf4de41918d4b127fa5b077188b8c7ba36abd61R2173) which is then sent to the server.

find an event by `display_name` is not a good idea. Two events can have the same display name (for whatever reason) but they will always have a different `short_name`.

I'd suggest you to:

1. revert the modification on the `admin-application.js` file
2. revert the modification on the `EventRepository`
3. find a better way to **display** the right value. I.e. adding an **additional** property in the scope (`$scope.eventDisplayName`?) with the right value to display
4. find the right place in the HTML template / JS code where we use `$scope.eventName` and we should use `$scope.eventDisplayName` instead
5. test and see if this solves the issue

**Comment by ved-asole** [comment]
Sure, I'm on it

**Comment by ved-asole** [comment]
Hi @cbellone, I have updated the code to show the display name on the Angular UI screen and updated the backend code to get the displayName while sending the email. Please approve the PR.

**Review by cbellone — APPROVED** [review]

**Comment by cbellone** [comment]
Approved and merged. Thank you!

**Comment by ved-asole** [comment]
Thanks @cbellone for giving me this opportunity to contribute to the project 😊

**Comment by ved-asole** [comment]
Hi @cbellone, just had a small doubt. In the repository contributors section my id/name is not being shown. Is it some glitch or I have not followed the proper procedure to contribute to the repo?

**Comment by ved-asole** [comment]
Hi @cbellone, could you please suggest on the above issue?

**Comment by ved-asole** [comment]
Hi @cbellone , could you please suggest why my name is not coming in collaborators list?

**Comment by cbellone** [comment]
Hi, now you should be in the collaborators list.

**Comment by ved-asole** [comment]
Thanks @cbellone, looking forward to on more projects working with you 😄

**Pull request merged**
