### PR TITLE
Update public_de.properties

### PR DESCRIPTION
**Pull request by samuelstein**
Fix german translations

### CODE REVIEW

**Comment by cbellone** [comment]
Hi @samuelstein , thank you for this Pull Request!

We use POEditor as a "Single Source of Truth" for all additional languages (all but English)

We have some pending translations for German which we haven't imported yet. Before merging this Pull Request I must make sure to apply changes done on POEditor first. 

This could conflict with your modifications. Sorry...

There is another option though, if you could reapply your modifications [on POEditor](https://poeditor.com/join/project/ttBYTmPYdr), I could then integrate all modifications directly.

Please let me know how do you want to proceed, and apologies for the extra work...

Celestino

**Comment by samuelstein** [comment]
okay, thanks @cbellone. I can reapply them on POEditor

**Comment by cbellone** [comment]
perfect, thanks!! 
Just sign up on our [project page](https://poeditor.com/join/project/ttBYTmPYdr) and I'll give you access right away.

**Comment by samuelstein** [comment]
I did.
Would be great if you could mention in the documentation that this is the prefered way for translations.

**Comment by cbellone** [comment]
thank you for your contribution and your suggestion. We'll document the process as soon as possible.

Will close this PR since the modifications will be applied through POEditor. 

We'll add your first name under the [POEditor contributors](https://github.com/alfio-event/alf.io#translation-contributors-poeditor). If you like to add your github/twitter profile there, please feel free to provide a PR.

Thanks

**Pull request closed without merging**
