### PR TITLE
removed OkHttp dependency

### PR DESCRIPTION
**Pull request by RushikeshSawant**
Removed `OkHttpClient` dependency completely

### CODE REVIEW

**Comment by syjer** [comment]
Hi, @RushikeshSawant thank you for the PR.

About the missing support of "multipart/form-data", maybe using the ideas from https://stackoverflow.com/questions/46392160/java-9-httpclient-send-a-multipart-form-data-request  / https://golb.hplar.ch/2019/01/java-11-http-client.html#upload-with-multipart ?

**Comment by RushikeshSawant** [comment]
Hi @syjer , thanks for pointing to that idea!
I did come across that page, but didn't read through to the bottom of it- my bad.
Will look into to it, and update my PR. Cheers.

**Comment by RushikeshSawant** [comment]
@syjer removed `OkHttpClient` dependencies completely.

**Comment by syjer** [comment]
hi @RushikeshSawant , thank you for the PR, I'll do a review as soon as possible 👍

**Comment by syjer** [comment]
hi @RushikeshSawant , looks like everything is ok, we  will merge it in the master branch after the M2 release :). Thank you

**Pull request merged**
