### PR TITLE
Added docs for Mollie

### PR DESCRIPTION
**Pull request by StanMar-bit**
Added a simple guide how to configure Mollie for use in Alf.io as payment method.

### CODE REVIEW

**Comment by cbellone** [comment]
Hi, thank you very much for this! :+1: 

I believe it would be important to mention which payment methods are currently supported.
We currently don't support all payment methods because some of them are not compatible with our workflow. 

You can find the list of supported methods here:
https://github.com/alfio-event/alf.io/blob/master/src/main/java/alfio/manager/payment/MollieWebhookPaymentManager.java#L79:L87

WDYT? Could you please add it?
thanks in advance!

**Comment by StanMar-bit** [comment]
Hi,
Thanks for your response happy to contribute.
Very good idea. I'm going to add it to the doc.
I will let you know when I have changed it :)

**Comment by StanMar-bit** [comment]
Hi @cbellone,
What would you think of a guide for deployment with Docker?
That's currently the environment I'm using for the fundraiser and it took quite a while to figure everything out.

Thanks in advance.

Stan

**Comment by cbellone** [comment]
> What would you think of a guide for deployment with Docker?
That's currently the environment I'm using for the fundraiser and it took quite a while to figure everything out.

yes, that's something that would be great to have in our docs. Can you please create a separate PR for that? TIA

please let me know if you'd be able to update this PR with the requested changes to the mollie doc, so that we can merge it. Thanks!!

**Review by cbellone — APPROVED** [review]

**Comment by cbellone** [comment]
merged. Thank you!

**Pull request merged**
