### PR TITLE
Create admin_pt_BR.properties

### PR DESCRIPTION
**Pull request by jonatasemidio**
Brazilian version of admin's properties.

### CODE REVIEW

**Comment by cbellone** [comment]
Hi @jonatasemidio, 
thank you very much for your contribution!

In order to add and enable a new language we need the translations for the following files:
- public.properties 
- admin.properties <-- already done! Thank you!

Do you have any plans to translate also the main file  "public.properties"? If yes, please could you add it to this PR?

Thank you!
Celestino

**Comment by jonatasemidio** [comment]
Yep!

Em dom, 6 de dez de 2015 4:46 PM, Celestino Bellone <
notifications@github.com> escreveu:

**Comment by jonatasemidio** [comment]
@cbellone 
The travis get 1 errored check 
> Could not resolve all dependencies for configuration ':classpath'.

https://travis-ci.org/exteso/alf.io/jobs/95322611

I'm new with travis... In this case, what I need to do?

**Comment by syjer** [comment]
@jonatasemidio  I've restarted the build and it seems to work correctly now. Maybe the network had some kind of problem on the travis side :).

**Comment by mg-1999** [comment]
Any update on this? Tests are passing now so it could be merged.

**Comment by cbellone** [comment]
The PR is not yet complete. Since the public_pt_BR.properties file is not fully translated, I was waiting a more complete version before merging it. 
@jonatasemidio, do you have any news about that?

Thank you!

**Comment by syjer** [comment]
closed for inactivity

**Pull request closed without merging**
