### PR TITLE
implement barcode reader listener #445

### PR DESCRIPTION
**Pull request by syjer**
Should be tested with a true barcode reader

### CODE REVIEW

**Comment by digitall-it** [comment]
I know that this and #688 are being incorporated in M2. I have installed it for a non profit organization venue for helping talented students in chef schools in Italy.

I currently had to use M1 that has not this functionality. May I please ask to release early an intermediate M1 with only the barcode features (both printing and HMI scanning) so we could use it? That would be very helpful for us. Thank you for taking this request in consideration, and for producing this free software.

**Comment by syjer** [comment]
hi @digitall-it , if you only need scanning, I would advise to use the mobile app (see tutorial at https://alf.io/tutorials/check-in/ (there is a IOS app too).

If you need to print the badge, then the only way currently is using alf.io-PI ( https://github.com/alfio-event/alf.io-PI/ ) which currently lack the documentation (it will come soon!).

**Comment by digitall-it** [comment]
I've tried the app and had some problems with it so couldn't yet use it (but I will open an issue for that, I hope it's only a minor configuration problem). The venue will receive many hosts, and we already have the scanner and a wired computer because the wireless connection is spotty. We would not like to subtract funds for the alf.io-PI and are going to the cheapest options we could (the scanner went for 19€ on Amazon) to check-in a reliable way a large quantity of people.

I would love to give them the barcode option, and it seems to be ready. I know I am asking much in this end of july request, so, please pardon my actions.

**Comment by syjer** [comment]
@digitall-it , I understand the issue :).

Could you please write in the mailing list (https://groups.google.com/forum/#!forum/alfio) to ask for an intermediate release, as this PR is not really the correct venue :).

Thank you.

**Comment by digitall-it** [comment]
Thank you @syjer for your prompt response. I summarized my problems with the iOS app into issue #701. 

I understand that this is not the right place to ask for that, as mine is not a bug report or a feature request and was unpolite of me. I tried connecting to the mailing list but hadn't access with my email address giancarlodimassa@gmail.com. May I kindly ask for authorization?

**Comment by syjer** [comment]
>I understand that this is not the right place to ask for that, as mine is not a bug report or a feature request and was unpolite of me.

no problem at all :).

> tried connecting to the mailing list but hadn't access with my email 

I think that there is a "join" button somewhere?

**Comment by digitall-it** [comment]
No, the message I receive, in italian, follows:

> "Questo gruppo non esiste o non disponi dell'autorizzazione per accedervi. Se sai per certo che questo gruppo esiste, contatta il proprietario del gruppo e chiedi che ti conceda l'accesso.
> **RICARICA**"

that in english says like this:

> "This group does not exist or you do not have permission to access it. If you know for sure that this group exists, contact the group owner and ask them to grant you access.
> **RELOAD**"

**Comment by syjer** [comment]
@digitall-it could you recheck, I did some update of the configuration, if it does not work, I'll send you an invite

**Comment by digitall-it** [comment]
Not yet. Is it possible that [the URL](https://groups.google.com/forum/#!forum/alfio) I'm trying to access is not right?

**Comment by syjer** [comment]
@digitall-it the url is the correct, I've sent an invite

**Comment by digitall-it** [comment]
Done, in [this thread](https://groups.google.com/forum/#!topic/alfio/ZNJUdPosHFk). Thank you for taking this into consideration. I wouldn't ask if that wouldn't be a non profit.

**Pull request closed without merging**
