### PR TITLE
Add Turkish translations

### PR DESCRIPTION
**Pull request by mortendir**

### CODE REVIEW

**Comment by mortendir** [comment]
I have not been able to see the translations because of two things:

1. I'm not sure how to switch the admin locale
2. I cannot create an event without configuring a Maps integration. Do you have a test account to share?

**Comment by fbiville** [comment]
Note: this would be useful for https://hack-commit-pu.sh :)

**Comment by cbellone** [comment]
Hi @mortendir and @fbiville ,

thank you very much for the PR!

I've built and installed it on our test server (https://test.alf.io). Please DM me on Twitter (https://twitter.com/c_bellone/) if you want access to the Backoffice.

Please note that the PR as it is does not work. We need the following line to be added at the end of ConfigurationKeys (line ~210)

```java
TRANSLATION_OVERRIDE_VAT_TR("Override the default tax term TR: KDV", false, SettingCategory.TRANSLATIONS, ComponentType.TEXT, false, EnumSet.of(SYSTEM, ORGANIZATION, EVENT))
```
in order to use the Turkish language. This setting will be removed once we have full message properties customization

Back to your questions:

> I'm not sure how to switch the admin locale

you can't. Admin is not yet localized. The only localized text at the moment are headlines on the dashboard. We'll hopefully fix this in 2.0-M3 (see [roadmap](https://github.com/alfio-event/alf.io/issues/435))

> I cannot create an event without configuring a Maps integration

This has been fixed by https://github.com/alfio-event/alf.io/issues/637 . If you rebase your code, you should be able to create an event without maps' api keys

Thank you again!

**Comment by mortendir** [comment]
@cbellone thanks for your quick response.
I managed to get a preview locally (free event, no email/maps setup) and adjusted a few translations. One issue I have is with form validation messages: are they hardcoded in English?
Would it be possible to redeploy this branch against the test server so we can test events with a few more options?
Thanks a lot for your help!

**Comment by cbellone** [comment]
@mortendir deployed! :)

> One issue I have is with form validation messages: are they hardcoded in English?

If you mean this:

image

it is shown in English because your browser is in English

All the other messages should be localized. If that's not the case, can you please tell me how to reproduce the issue?

Thanks!

**Comment by mortendir** [comment]
@cbellone those were indeed the browser built-in validation messages and my browser is configured to use the English locale, my bad!
I believe the Turkish translations are now in an acceptable state. Feel free to squash my commits and merge them. Thanks a lot for your reactivity!

**Comment by cbellone** [comment]
Merged. Thank you very much!! :-)

I have imported the Turkish language on Poeditor, under our project https://poeditor.com/join/project/ttBYTmPYdr

It would be fantastic if you could register there as maintainer of the language. To do that, just ask to join the project and we'll grant you access on Turkish

Thank you again for your contribution! The new language will be available in the next few days on hack-commit-push's instance :)

**Pull request merged**
