### PR TITLE
integrated send grid mailer

### PR DESCRIPTION
**Pull request by sergyer**

### CODE REVIEW

**Comment by syjer** [comment]
hi @sergyer , thank you for the PR 👍 , I'll have a look after we will do the M2 release

**Comment by sergyer** [comment]
Hi @syjer , very cool, will wait for feedbacks))  meanwhile I will start the integration of the next provider.
When do you plan to do a release?

**Comment by syjer** [comment]
hi @sergyer , sorry for the delayed response, I was away.

Everything seems ok. 

Maybe, if you want to align with the others implemented mailers (like https://github.com/alfio-event/alf.io/blob/master/src/main/java/alfio/manager/system/MailjetMailer.java ), you could call directly the API rest instead of using the sendgrid library? This way we could avoid to import yet another http client as a transitive dependency (apache commons http in this case).

What do you think ?

**Comment by sergyer** [comment]
Hi @syjer, thanks for the review,  indeed I agree with, let's keep things consistent. I have done refactoring, please review one more time.

**Comment by syjer** [comment]
hi @sergyer , thank you for the refactoring :+1: , btw, the build is failing because the file `SendGridMailer.java` is  missing the license header, once you have added it, I'll merge your PR .

Thank you again :)

**Comment by sergyer** [comment]
@syjer  Done ;)

**Comment by syjer** [comment]
@sergyer thank you :+1:

**Pull request merged**
