### PR TITLE
Add new Column in configuration table

### PR DESCRIPTION
**Pull request by shrutimandaliya**
Added new column in configuration table last modified date

### CODE REVIEW

**Comment by syjer** [comment]
hi @shrutimandaliya , what are you trying to do?

**Comment by shrutimandaliya** [comment]
as per issue  #724 , I added new column in configuration table

**Comment by syjer** [comment]
@shrutimandaliya why did you add the hibernate annotation? We don't use hibernate, so it will not work.

**Comment by syjer** [comment]
Additionally, I've noticed you are trying to fix the issue in a single PR, we cannot accept this PR.

You should only fix one issue at a time.

**Comment by syjer** [comment]
closing this PR, as it try to fix 2 issues at the same time and thus we cannot accept it.

**Pull request closed without merging**
